# Generated by Django 4.0.5 on 2022-06-18 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerimage',
            old_name='image_field',
            new_name='test',
        ),
    ]
