# Generated by Django 4.0.5 on 2022-06-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_image_field_customerimage_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.ImageField(upload_to='uploads/')),
            ],
        ),
        migrations.RenameField(
            model_name='customerimage',
            old_name='test',
            new_name='image_field',
        ),
    ]
