# Generated by Django 4.0.5 on 2022-06-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_testimage_rename_test_customerimage_image_field'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimage',
            old_name='test',
            new_name='image_field',
        ),
        migrations.AddField(
            model_name='testimage',
            name='image_name',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
