# Generated by Django 4.0.5 on 2022-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_test_testimage_image_field_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='test/')),
            ],
        ),
    ]
