# Generated by Django 4.0.5 on 2022-06-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_image_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('src', models.ImageField(upload_to='test/u<django.db.models.fields.CharField>/')),
            ],
        ),
    ]
